import type { Metadata } from "next";
import "./globals.css";
import { ReactLenis } from "@/public/lenis";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Fuworx Innovations",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ReactLenis root>
        <body className={`antialiased`}>
          <Navigation />
          {children}
          <Footer />
        </body>
      </ReactLenis>
    </html>
  );
}
